  spring:
    h2.console:
      enabled: true
      path: '/console'
    datasource :
      url : 'jdbc:h2:file:~/Bartek/IdeaProjects/UdemySpringAppNewCourse/springTest-db'
    jpa:
      database.platform: 'jpa.database-platform=org.hibernate.dialect.H2Dialect'
  task.allowMultipleTaskFromTemplate: false
