  spring:
    flyway:
      baseline-on-migrate: true
    h2.console:
      enabled: true
      path: '/console'
    datasource :
      url : 'jdbc:h2:file:~/Bartek/IdeaProjects/UdemySpringAppNewCourse/testDatabase-db'
    jpa:
      hibernate:
        ddl-auto: validate
  management:
      endpoints:
        web:
          exposure:
            include: '*'

